QUESTION_KEY = "question"
ID_KEY = "id"
ANSWER_KEY = "answer"
GOLD_PASSAGE_KEY = "gold_passages"
PASSAGE_ID_KEY = "passages_id"
PASSAGE_TITLE_KEY = "passages_title"
PASSAGE_TEXT_KEY = "passages_text"
GENERATION_KEY = "generation"
LOGITS_KEY = "logits"
EVAL_LOSS_KEY = "eval_loss"
QA_PAIRS_KEY = "qa_pairs"
ORIGINAL_ID_KEY = "original_id"

HF_ACCESS_TOKEN = "INSERT_ACCESS_TOKEN_HERE"
